# Generated by Django 2.1 on 2021-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
    ]
